[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "backend/**",
  "Dockerfile",
  "railway.migrations.toml"
]

[deploy]
startCommand = "sh -c \"npm run migration:run && echo Migrations completed\""
cronSchedule = "0 3 * * *"
restartPolicyType = "NEVER"
