[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "cloudflare/secure-document-upload/clamav/**"
]

[deploy]
startCommand = "/app/entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
