[build]
builder = "DOCKERFILE"
dockerfilePath = "ops/docker/Dockerfile"
watchPatterns = [
  "backend/**",
  "ops/docker/Dockerfile",
  "ops/railway/railway.migrations.toml"
]

[deploy]
startCommand = "sh -c \"npm run migration:run && echo Migrations completed\""
cronSchedule = "0 3 * * *"
restartPolicyType = "NEVER"
